### ISSUE TITLE
Incompatability With Astral Sorcery

### ISSUE THREAD

**Issue by EmosewaPixel** [Shadows-of-Fire/FastWorkbench#1]
The most basic things from Astral Sorcery are made via a Crafting Table connected to a Floating Crystal. However, this mod conflicts with that crafting system. Is it possible to fix or add a check for that?

**Comment by Shadows-of-Fire** [comment]
Waiting for a response from hellfire to figure out what to do

**Comment by Shadows-of-Fire** [comment]
Alright I think I've fixed this issue, now I need to address a sync issue caused by fixing this one.

**Comment by Shadows-of-Fire** [comment]
https://minecraft.curseforge.com/projects/fastworkbench/files/2535231
