### ISSUE TITLE
Ticking Memory Connection

### ISSUE THREAD

**Issue by O13SC3N3** [Shadows-of-Fire/FastWorkbench#10]
1.12.2 Minecraft Forge 2768

https://paste.dimdev.org/igukayujax.mccrash

Not sure whats going on back tracking to see if another mod is Involved but the error is stating Patchouli and FastWorkBench. On World Creation and Modpack load everything is fine, everything loads smooth and the console reports errors with Advancements which seems to be the norm. However once save and quitting which is also fine, when you got to reopen the world It throws this error and will not reload. You can create a world just fine and play, until you save and exit and want to play again.

Posted at Both.

**Comment by Shadows-of-Fire** [comment]
Has nothing to do with FB, i'm only in the stacktrace because i have to have a hook at that location, but i don't actually change any functionality, and i certainly dont change anything relating to advancements.
