### ISSUE TITLE
Mod removes green recipe book icon when it shouldn't (?)

### ISSUE THREAD

**Issue by NerArth** [Shadows-of-Fire/FastWorkbench#100]
Although we have:

`B:"Remove Recipe Book Button"=false`

The icon is not showing up for players on our 1.19.2 forge server; I'm not sure what the cause for this is, as it seems to be working in single-player and LAN hosting.

Clients also have the setting matched to the server.

Installed FW version is 1.19.2-7.1.3

**Comment by RoyalReject** [comment]
You might have other mods that include this feature are you playing a custom pack? or something already on curseforge?

**Comment by NerArth** [comment]
I'm using a custom pack I have put together and which is available on Curse (Nermagitek is the pack name)

You should be able to see the modlist on this page for the current modpack release:
https://legacy.curseforge.com/minecraft/modpacks/nermagitek/files/4590389

Is there any way I can log something that might indicate why the book icon isn't there even with the setting correctly set to false both on clients and the server?

**Comment by Shadows-of-Fire** [comment]
If the setting is false on the client, FB will not remove the button <https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.19/src/main/java/shadows/fastbench/ClientHandler.java#L26>

The setting does nothing on the server.

However, there are other mods known to remove it as well.  Unfortunately that list isn't known to me.
