### ISSUE TITLE
[1.19.2] Incompatibility with Sophisticated Storage

### ISSUE THREAD

**Issue by sigmastar00** [Shadows-of-Fire/FastWorkbench#101]
Forge: 43.2.14
Fast Workbench: 7.1.3
Placebo: 7.2.0
Sophisticated Core: 1.19.2-0.5.77.346
Sophisticated Storage: 1.19.2-0.8.32.510

Sophisticated storage has a recipe for converting between its barrels with the standard model, and and alternate model with a flat top. This recipe causes a client crash if you attempt to convert more than one barrel at a time by shift clicking the output. This crash only occurs when FastWorkbench is installed.

Crash report: https://hastebin.com/share/fuxihasivi.php

**Comment by Shadows-of-Fire** [comment]
The error message clearly states that SS is violating the recipe contract: `java.lang.RuntimeException: A recipe matched but produced an empty output - Offending Recipe : sophisticatedstorage:flat_top_barrel_toggle - This is NOT a bug in FastWorkbench!`

**Comment by sigmastar00** [comment]
Ah I missed that part, my bad.
