### ISSUE TITLE
[1.19.2] Recipe book config not synced to client

### ISSUE THREAD

**Issue by sigmastar00** [Shadows-of-Fire/FastWorkbench#102]
Installed mods:
Forge 43.2.14
Fast Workbench 7.1.3
Placebo 7.2.0

When the config option "Remove Recipe Book Button" is set to false, the recipe book remains absent when joining a server. Joining a singleplayer world with the same option set to false correctly shows the recipe book. Joining a singleplayer world, and then a server afterwards also correctly shows the recipe book on the server.

**Comment by katubug** [comment]
Having this same issue reported to me by modpack users.

**Comment by Shadows-of-Fire** [comment]
That config is clientside only, so it does not sync s2c.  There are other mods that also remove the book though.

**Comment by sigmastar00** [comment]
The issue is that the recipe book is *supposed* to be there, but it isn't until you join a singleplayer world. The config is not being respected, calling it a syncing issue is probably incorrect but I wasn't sure how else to describe it.

**Comment by Shadows-of-Fire** [comment]
Ah, okay, yeah this might be an actual issue. I don't read the config on startup and only on reload (which is clientside boot of a world).

Fixed for 7.1.4
