### ISSUE TITLE
Crafting recipe result disappears after pooled updates run twice due to mod conflict

### ISSUE THREAD

**Issue by Eggwynn** [Shadows-of-Fire/FastWorkbench#106]
Minecraft: 1.20.1
FML: forge-1.20.1-47.2.0
MOD: fastworkbench-1.20.1-8.0.2.jar
Occurs in both Singleplayer and Multiplayer

As the title suggests, valid crafting recipes show the result for a single tick before disappearing. Changing the 3rd config option (I:"Grid Update Interval") to 100, I noticed that the result would first not appear, then appear for 100 ticks, then disappear permanently, so I figure whatever is causing the issue is the pool of crafting grid updates.

Only occurs when running with other mods, I've yet to isolate which one specifically (already tried problem mods like Silent Gear and Polymorph)

Uninstalling Fast Workbench isn't an option due to it seemingly fixing a massive CPU sink in the crafting recipe manager (picked up by Spark profiler, I can post the screenshot if needed)

I'm aware similar bugs have come up (#58), but I'm fairly certain this is somewhat different and arises from a mod conflict. The problem is, my pack has 300+ mods and it's taking me a massive amount of time to troubleshoot. I figured I'd shoot my shot here and see if there's any known fix/mod conflict to save me the time. If not, figured it might be worth posting here anyway since it occurs on the latest version of the mod. 

Super inexperienced with this kind of stuff sorry if there is an obvious fix

![image](https://github.com/Shadows-of-Fire/FastWorkbench/assets/157969896/1d70a672-d6a3-4ede-8f43-4803ef83d060)

**Comment by Shadows-of-Fire** [comment]
Unfortunately there's nothing I can do to triage this on my end.  If you can isolate the offending mod, I can investigate further.
