### ISSUE TITLE
Duplication of items in v8.0.3

### ISSUE THREAD

**Issue by DragonS0u1623** [Shadows-of-Fire/FastWorkbench#108]
While on a server that was updated to the latest version, I found that the recipes would duplicate the items in the crafting fields. It applied to both inventory and crafting table crafting grids, and when I rolled back the version to v8.0.2 the duplication bug was gone. During testing I had 2 blocks of gold, when shift clicking the result I managed to get 16 **STACKS** of 4096 ( 16 slots of 2x Gold upgrade Sophistocated Storage chests) of Gold blocks in addition to the 3 stacks of gold ingots.
Below is an image of the amount of blocks received, I ended up trashing a lot of them when I realized that there were still over a thousand more on the ground.
![2024-02-12_00 14 26](https://github.com/Shadows-of-Fire/FastWorkbench/assets/24501666/6ce3b67a-88dd-4ede-aff6-b4166bf923c3)

**Comment by Shadows-of-Fire** [comment]
I'm uh, not sure how that makes any sense.  The only change there was removing an override that was identical to vanilla minus the call to the new `awardUsedRecipes` method, which needed to be called anyway.
I suspect mixins are afoot...

**Comment by Shadows-of-Fire** [comment]
Oh, no, that's why - `awardUsedRecipes` nulls out the cached recipe, for some godforsaken reason.

Why is vanilla's crafting grid code so awful

**Comment by DragonS0u1623** [comment]
This is the greatest thing I've read today
