### ISSUE TITLE
Mod causing crafted item to disappear from crafting table (neoforge 1.21.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [Shadows-of-Fire/FastWorkbench#109]
![image](https://github.com/user-attachments/assets/836a2d24-92ab-4ed6-9f23-3915a329a803) with the mod removed
![image](https://github.com/user-attachments/assets/56d1ed2c-8fd6-492e-ad26-f3f86f419c25) with the mod added (clicking the crafted thing still gives the item tho)

**Comment by Shadows-of-Fire** [comment]
What other mods do you have installed that are editing the crafting table?  This doesn't happen in isolation.

**Comment by VaporeonScripts** [comment]
visual workbench (i tried to remove it but issue still there)
crafting tweaks

**Comment by Shadows-of-Fire** [comment]
Test without Crafting Tweaks. I don't think the issue is there though. If it isn't, you'll need to source the offending mod from your instance.

**Comment by VaporeonScripts** [comment]
kinda sure that crafting tweaks got nothing to do with that,as a modpack named craftoria got fast workbench and crafting tweaks too with no problems

**Comment by VaporeonScripts** [comment]
found the solution, the mod causing items to disappear from crafting table is tool trims
https://modrinth.com/datapack/tool-trims

**Comment by VaporeonScripts** [comment]
~another mod is causing the issue too :skull: 
(nevermind, it just didnt really craft anything :skull: )

**Comment by CorneliusCornbread** [comment]
> ~another mod is causing the issue too 💀 (nevermind, it just didnt really craft anything 💀 )

Do you remember what mod you removed to resolve this issue? I'm running into the same issue but I'm unsure as to which mod I have installed that's causing it.

**Comment by VaporeonScripts** [comment]
Tool trims
