### ISSUE TITLE
Astral Sorcery incompatibilty is back.

### ISSUE THREAD

**Issue by DelviousCrafts** [Shadows-of-Fire/FastWorkbench#14]
This issue seems to have returned. The fast workbench no longer makes a luminous crafting table with standard interaction with a shrine crystal.

**Comment by Shadows-of-Fire** [comment]
mod versions? (as+fb+forge)

**Comment by DelviousCrafts** [comment]
my apologies. Mod version FastWorkbench 1.7.1, Astral sorcery 1.10.18, Forge 14.23.5.2831

**Comment by Shadows-of-Fire** [comment]
does disabling experimental shift crafting in the config resolve this issue?

**Comment by DelviousCrafts** [comment]
This does not seem to fix the issue on server, working on checking a single player world

**Comment by DelviousCrafts** [comment]
This is also not correcting the issue on single player worlds.

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce.  And considering nothing has changed from my end or AS's end, it's very likely you have something else breaking it.

**Comment by DelviousCrafts** [comment]
Ok. Hey thanks for checking. I'll see what else I can dig up.
