### ISSUE TITLE
Removes JEI "+" Button

### ISSUE THREAD

**Issue by JohnC94** [Shadows-of-Fire/FastWorkbench#2]
Forge: 14.23.2.2619
FastWorkBench: 1.12.2-1.1.1
Modlist: https://i.imgur.com/juRC8hM.png
Single Player

When FastWorkbench is disabled. https://i.imgur.com/A2yAIrv.gifv

When FastWorkbench is enabled. https://i.imgur.com/ffIRnha.gifv

I'm aware this might be something specific to me, but I figured I should report it anyways.

**Comment by Shadows-of-Fire** [comment]
Ah.  It appears there's an API call to fix this.  Let me figure out how that works.

**Comment by yepidoodles** [comment]
I've just added this to my 1.12.2 modpack and server, and on both multiplayer and single player, the + does not show. 
Forge: 2707
FastWorkBench: 1.5.0
I can send you the modpack if you need it.

**Comment by Shadows-of-Fire** [comment]
Again?  Theres no way...  This issue never seems to go away, does it.

**Comment by Shadows-of-Fire** [comment]
Well... I can't reproduce it being missing.  Not in SSP or on dedicated, nor in dev environment.

**Comment by yepidoodles** [comment]
So, it looks like the player who reported it to me was being an idiot, it's actually fine (just double checked myself), sorry for the scare!
