### ISSUE TITLE
Cant open crafting table

### ISSUE THREAD

**Issue by MeinKraft** [Shadows-of-Fire/FastWorkbench#22]
Forge 28.0.14
FastWorkbench 1.14.4-2.0.1
JEI Not Installed

Crafting tables open then immediately close gui when FastWorkbench is installed. Everything is normal when FastWorkbench is removed

**Comment by Shadows-of-Fire** [comment]
Try using forge 28.0.13 if possible.  Something has probanly changed that needs to ve updatedml

**Comment by MeinKraft** [comment]
forge 28.0.13 fails too. With just Forge and Fastworkbench (and Placebo)

Forge 28.0.13 and FastWorkbench 2.0.0 FAIL
Forge 28.0.13 and FastWorkbench 2.0.1 FAIL

**Comment by NillerMedDild** [comment]
28.0.21 also fails.

**Comment by Shadows-of-Fire** [comment]
Is there any sort of log message or other error?  This appears to only happen in production and I havent been able to test yet

**Comment by EmosewaPixel** [comment]
There appear to be no errors in the log.

**Comment by Shadows-of-Fire** [comment]
This is actually a forge bug, it looks like...  I was making a check against Blocks.CRAFTING_TABLE, which isn't being properly updated to my replacement (but only in production)

**Comment by Shadows-of-Fire** [comment]
This would also be the cause of #21 and #23

**Comment by Shadows-of-Fire** [comment]
MinecraftForge/MinecraftForge/issues/5984
