### ISSUE TITLE
Client crash. "java.lang.NoSuchMethodError:"

### ISSUE THREAD

**Issue by Wissi** [Shadows-of-Fire/FastWorkbench#26]
Awesome line of mods, love it for our modpack and server.

We are getting this error in SP tests. 
Crash log [here](https://gist.github.com/Wissi/d65a5668db960388bfa33b48a5aae316).

When using vanilla crafting table.
It seems to happen only when we have [Crafting Tweaks](https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks) installed as well.

Forge-28.0.81.jar
FastFurnace-1.14.4-2.0.0.jar
CraftingTweaks_1.14.4-10.1.3.jar  (in case it helps)

Hope it helps to get full compatibility. Thanks.

**Comment by Shadows-of-Fire** [comment]
You're using an outdated version of FB, which references methods that have since been removed from placebo.  All you should need to do is upsate.

**Comment by Wissi** [comment]
I posted the wrong file (FastFurnace-1.14.4-2.0.0.jar).
It's `FastWorkbench-1.14.4-2.0.3.jar`
And yes it is the not the latest.

Thank you so much for pointing it out and answering so quick.
Working perfectly fine w/latest `FastWorkbench-1.14.4-2.1.0.jar`

Awesome work.
