### ISSUE TITLE
ItemCraftedEvent not firing on shift-click crafting

### ISSUE THREAD

**Issue by Blargerist** [Shadows-of-Fire/FastWorkbench#3]
Triumph on-crafting trigger isn't working with FastWorkbench when shift-clicking. I did some minor testing, and it appears the event isn't being fired on shift-click. Works fine on normal click.

**Comment by Shadows-of-Fire** [comment]
Thats odd.  The slot changes shouldn't impact that event, and the shift click not firing is even more complicated.  I don't change how shift clicks are handled at all.  
But if vanilla handles that properly then something is up.

**Comment by Shadows-of-Fire** [comment]
Oh goddamnit.  This is all because I was forced to extend SlotCrafting for compat.  It was working before just fine.  Blehhhhhhhhhhhhhhhhhhh.
