### ISSUE TITLE
Unstackable items get voided.

### ISSUE THREAD

**Issue by Darkere** [Shadows-of-Fire/FastWorkbench#30]
Not 100% sure this is on you but I don't think any other mods are messing with the vanilla crafting table.

https://gfycat.com/AnguishedDelightfulBeetle

Works with other items like pickaxes too. 

Have not tested Singleplayer

FastWorkbench-1.14.4-2.1.4
Forge. 28.1.87

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce on dedicated https://pcpartpicker.com/list/tC6H27

**Comment by Darkere** [comment]
Well the items need to have NBT for it to work. 

But yeah also disappears when removing Crafttweaker :/
