### ISSUE TITLE
Dupe with Everlasting Abilities

### ISSUE THREAD

**Issue by Darkere** [Shadows-of-Fire/FastWorkbench#31]
This one works fine in other crafting tables. That's why I'm reporting here and not on everlasting abilities. From what I've heard 3 ability bottles are supposed to combine into one random one. 

https://gfycat.com/FlamboyantLikableBronco
Have not tested Singleplayer
FastWorkbench-1.14.4-2.1.4
Forge. 28.1.87
Pack: Enigmatica 4

**Comment by Shadows-of-Fire** [comment]
Can't reproduce that either, might be related to whatever is breaking stuff in #30

**Comment by Darkere** [comment]
kk gonna try and figure out what might be causing it then :/

**Comment by Darkere** [comment]
Appears to be caused by CraftTweaker.
