### ISSUE TITLE
Looking up a recipe in JEI hides items inside the Crafting table

### ISSUE THREAD

**Issue by Darkere** [Shadows-of-Fire/FastWorkbench#32]
This time I tested with just fast workbench and JEI :)

https://gfycat.com/SlimyElementaryIrishwolfhound

Forge: 28.1.87
FastWorkbench-1.14.4-2.1.4
jei-1.14.4-6.0.0.25
Placebo-1.14.4-2.3.5

**Comment by Shadows-of-Fire** [comment]
@mezz any idea what causes that?

**Comment by FreeFull** [comment]
I still get this issue even without FastWorkbench, so it's very probably only a JEI bug. It seems it's not hiding the items, but visually reverting to a previous state instead of the proper one.

**Comment by Shadows-of-Fire** [comment]
Someone should probably bring it up with JEI then, but if it's not related here I'll close it
