### ISSUE TITLE
how do i stop the recipe book from being snapped out of existance

### ISSUE THREAD

**Issue by bayleywrayYT** [Shadows-of-Fire/FastWorkbench#33]
so my friend uses fastworkbench on his server but I want to use the recipe book but to join I need fastworkbench so how would one go about using the recipe book in the server with fastworkbench installed?

**Comment by bayleywrayYT** [comment]
fast workbench ver 1.6.1

**Comment by Shadows-of-Fire** [comment]
Both the server and your client config would need to have the recipe book enabled.  Having it enabled will make logins take longer, so you should probably just use jei and continue to let it be disabled.
