### ISSUE TITLE
Game sites 3 mods that crash it, this mod is one...

### ISSUE THREAD

**Issue by RepoDraghon** [Shadows-of-Fire/FastWorkbench#35]
https://paste.dimdev.org/tigucevava.mccrash

[Minecraft 1.12.2 Error.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/4253007/Minecraft.1.12.2.Error.txt)

**Comment by Shadows-of-Fire** [comment]
that's a bug in ftbmoney

**Comment by RepoDraghon** [comment]
Ok thank you.
