### ISSUE TITLE
Reloaded recipes don't show output

### ISSUE THREAD

**Issue by NielsPilgaard** [Shadows-of-Fire/FastWorkbench#36]
When making a new recipe with CraftTweaker, using `/reload` to see it, and then placing the input items into a FastWorkbench to see if it works, the output will not be rendered.

The recipe does however work correctly when the empty output area is clicked.

**Comment by Shadows-of-Fire** [comment]
Is the output shown correctly if that recipe is loaded during startup?

**Comment by NielsPilgaard** [comment]
Yep.

**Comment by Shadows-of-Fire** [comment]
Does that persist on a vanilla workbench?
I don't think FB does anything that would clash with a reload unless something wasn't being synced properly from the reload.

**Comment by NielsPilgaard** [comment]
Hard to tell, doesn't FastWorkbench completely remove the vanilla workbench? ^^'
I'll have a look tomorrow :)

**Comment by NielsPilgaard** [comment]
I cannot reproduce it in a vanilla Crafting Table. But I'll just close the issue, it's really minor, I mostly wanted to let you know in case it was an easy fix.
