### ISSUE TITLE
Incompatibility with Simple Storage Network mod

### ISSUE THREAD

**Issue by Alyaqdhans** [Shadows-of-Fire/FastWorkbench#41]
When I try "Simple Storage Network" mod without "FastWorkbench" I can't shift click the storage remotes
but with "FastWorkbench" I can, except a single remote that's called "Simple Storage Remote".

**Comment by Shadows-of-Fire** [comment]
fb doesnt do anything to other mods, so, thats probably on them

**Comment by AlyaqdhanZ** [comment]
Try it first.
