### ISSUE TITLE
[1.16.1] Spam in console when crafting any item in Inventory or Crafting Table.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/FastWorkbench#43]
Title^

**MC:** 1.16.1
**Forge:** 32.0.63
**FastWorkBench Version:** 4.1.0

**Logs:** https://gist.github.com/Gbergz/64ae8c39198e8e4eb0a59f9fdf0347a0 (At the bottom.)

**Comment by Shadows-of-Fire** [comment]
🤦
