### ISSUE TITLE
[1.15.2] Issue when selecting alternate recipe with Polymorph

### ISSUE THREAD

**Issue by katubug** [Shadows-of-Fire/FastWorkbench#44]
Hello! I'm using FastWorkbench 3.1.1 and Polymorph 0.6 on Forge 31.2.31, and I'm having an issue where recipes other than the primary one don't seem to be selectable. The Polymorph icon is visible, both recipes show up in the GUI, but regardless of which one is clicked on, the output slot only ever shows the first option.

Disabling FastWorkbench allows the selection to function as intended, so I believe it is a conflict with just these two mods.

Let me know if I can get you any other information! Thanks very much!

**Comment by Shadows-of-Fire** [comment]
Polymorph likely has not updated to the changes made in FB 3.1, you'll need to ask them to update their support

**Comment by katubug** [comment]
Ah, cool, will do! Thanks!
