### ISSUE TITLE
Replacing PlayerList instance has potential risk.

### ISSUE THREAD

**Issue by IzzelAliz** [Shadows-of-Fire/FastWorkbench#45]
Some mods may inject code into PlayerList (for example https://github.com/IzzelAliz/Arclight/issues/23), and this will cause a re-initialize issue.
This can be implemented more gracefully, like subscribing to `net.minecraftforge.event.entity.player.PlayerEvent.LoadFromFile`, and do modifications to player (and its recipe book) here.

**Comment by Shadows-of-Fire** [comment]
Closed via d27e2b8
