### ISSUE TITLE
[1.16] Won't load on latest version of Forge

### ISSUE THREAD

**Issue by FynnWaelsing** [Shadows-of-Fire/FastWorkbench#46]
FastWorkbench version: FastWorkbench-1.16.1-4.1.1
Forge version: 32.0.93
Latest log: https://pastebin.com/Dmes4L56

I get an error message saying that FastWorkbench hasn't loaded correctly on the latest (93) version of Forge. The mod loads correctly on build 88.

**Comment by Shadows-of-Fire** [comment]
Forge has made breaking changes, you should just use 88 for now.

**Comment by FynnWaelsing** [comment]
Got it. No big deal; just wanted to give you a heads-up.

**Comment by xdjoshuaaz** [comment]
@Shadows-of-Fire I've made a PR (#49) that fixes the `@SubscribeEvent`-related exceptions described in the crash report of this issue.
