### ISSUE TITLE
Crash when launching the game using version 1.15.2-3.1.1

### ISSUE THREAD

**Issue by slevder** [Shadows-of-Fire/FastWorkbench#48]
[crash-2020-07-30_12.12.18-client.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/5002783/crash-2020-07-30_12.12.18-client.txt)

**Comment by slevder** [comment]
Here is a copy paste of crash report:

> ---- Minecraft Crash Report ----
> // Hey, that tickles! Hehehe!
> 
> Time: 7/30/20 12:12 PM
> Description: Initializing game
> 
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78) ~[?:31.2] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231) ~[?:?] {re:classloading}
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189) ~[?:?] {re:classloading}
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191) ~[?:?] {re:classloading}
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:166) ~[minecraft-1.15.2-client.jar:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.2.0-launcher.jar:31.2] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50) [ForgeWrapper-1.4.2.jar:?] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] {}
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
> 	... 44 more
> Caused by: net.minecraftforge.fml.ModLoadingException: FastWorkbench has class loading errors
> §7net.minecraftforge.fml.DistExecutor.unsafeRunForDist(Ljava/util/function/Supplier;Ljava/util/function/Supplier;)Ljava/lang/Object;
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:77) ~[?:31.2] {re:classloading}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
> 	... 44 more
> Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.DistExecutor.unsafeRunForDist(Ljava/util/function/Supplier;Ljava/util/function/Supplier;)Ljava/lang/Object;
> 	at shadows.fastbench.FastBench.<clinit>(FastBench.java:49) ~[?:3.1.1] {re:classloading,pl:object_holder_definalize:A}
> 	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_261] {}
> 	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:71) ~[?:31.2] {re:classloading}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261] {}
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261] {}
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:73) ~[?:31.2] {re:classloading}
> 	... 44 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:78)
> 	at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:251)
> 	at net.minecraftforge.fml.ModLoader.lambda$buildMods$27(ModLoader.java:231)
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source)
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
> 	at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:233)
> 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$19(ModLoader.java:189)
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> 	at java.util.stream.ReferencePipeline.collect(Unknown Source)
> 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:191)
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:97)
> 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113)
> 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:97)
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(SourceFile:166)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.15.2
> 	Minecraft Version ID: 1.15.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_261, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 2148943968 bytes (2049 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
> 	CPUs: 8
> 	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m
> 	ModLauncher: 5.1.0+69+master.79f13f7
> 	ModLauncher launch target: fmlclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
> 		/forge-1.15.2-31.2.0-launcher.jar object_holder_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.0-launcher.jar runtime_enum_extender PLUGINSERVICE 
> 		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
> 		/forge-1.15.2-31.2.0-launcher.jar capability_inject_definalize PLUGINSERVICE 
> 		/forge-1.15.2-31.2.0-launcher.jar runtimedistcleaner PLUGINSERVICE 
> 		/forge-1.15.2-31.2.0-launcher.jar fml TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
> 		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
> 	FML: 31.2
> 	Forge: net.minecraftforge:31.2.0
> 	FML Language Providers: 
> 		javafml@31.2
> 		minecraft@1
> 	Mod List: ~~ERROR~~ NullPointerException: null
> 	Launched Version: MultiMC5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: AMD Radeon RX 5700 GL version 4.6.14736 Compatibility Profile Context 20.7.2 27.20.2001.9003, ATI Technologies Inc.
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by Shadows-of-Fire** [comment]
you're using an outdated forge version

**Comment by slevder** [comment]
Thank you! I will update to the latest forge version
