### ISSUE TITLE
Crafting table not displaying

### ISSUE THREAD

**Issue by Ceifeire** [Shadows-of-Fire/FastWorkbench#50]
Hi I am having an issue with the crafting table on a multiplayer server. All players are experiencing this issue with the vanilla texture pack. The crafting table looks like the picture below, purple and black. Any ideas why?

MC: 1.12.2
Forge: 14.23.5.2847
Fast Workbench: 1.7.3

![fast workbench issue](https://user-images.githubusercontent.com/38624271/92671650-d0eed600-f2e4-11ea-883c-396569b0abc4.png)

**Comment by Shadows-of-Fire** [comment]
That would mean you have either
A) Installed FB on only one side of the game (it is required on both client and server)
or B) Installed FB after crafting tables were already present in-world, in which case they need to be broken and re-placed.

**Comment by Ceifeire** [comment]
Thanks for the quick answer. I discovered that the server did not have it and am booting it up to check now.
