### ISSUE TITLE
Using both Quark Oddities Backpacks and FastWorkbench makes the game crash when crafting inside inventory 

### ISSUE THREAD

**Issue by Timolino456** [Shadows-of-Fire/FastWorkbench#51]
I'm posting this issue on both mods since I'm not sure who would have to fix it.
When having a backpack from Quark Oddities equipped and FastWorkbench installed, trying to put something into the crafting grid inside my inventory causes the game to freeze, "Saving chunks" and crash.

Here's the crash log: https://paste.ee/p/zlMlI

**Comment by Shadows-of-Fire** [comment]
Looks like using a quark backpack is always going to invalidate the fact that FB makes the player crafting grid faster, but I should be able to fix the crash.  I just hope it doesn't break anything else.
