### ISSUE TITLE
Astral Sorcery can be added to the list of compatible mods, maybe?

### ISSUE THREAD

**Issue by Moleculor** [Shadows-of-Fire/FastWorkbench#57]
![image](https://user-images.githubusercontent.com/3865976/100487877-7c334e00-30d0-11eb-9016-fe13602574c2.png)

Plopped a FastWorkbench down inside an Astral Sorcery shrine and it immediately converted it to the appropriate block, as it should.

You can probably add Astral Sorcery to your list of compatible mods? Though I don't know what other requirements exist to officially be on that list.

**Comment by Martijn-Bos** [comment]
In the modpack Valhesia 3, the FastWorkBench didnt convert. How to properly debug the reason, as stated above, a different issue?

**Comment by Moleculor** [comment]
> 
> 
> In the modpack Valhesia 3, the FastWorkBench didnt convert. How to properly debug the reason, as stated above, a different issue?

Likely the usual causes: You didn't find a naturally generated shrine, the crystal itself doesn't have a direct vertical line of sight to the sky, etc.

**Comment by Shadows-of-Fire** [comment]
I don't think this is an actual issue, astral works just fine with FB

**Comment by Moleculor** [comment]
Yeah. That's what I said?

You used to have a list of compatible mods. I think on CurseForge? *Ages* back when I made this issue. This was me suggesting you add Astral Sorcery to the list, since it wasn't on it.

I guess the alternative was to delete the list.
