### ISSUE TITLE
1.16.4 Silent Gear's repair kit misbehaves with FastWorkbench

### ISSUE THREAD

**Issue by FreeFull** [Shadows-of-Fire/FastWorkbench#58]
The following issue seems to only occur with FastWorkbench installed: https://github.com/SilentChaos512/Silent-Gear/issues/237

When a repair kit is being refilled by crafting it with a material, the output seems to only consider the materials that were there before the repair kit was put into the crafting slot.
For example, if you put in a repair kit in slot 1, cobble in slot 2 and cobble into slot 3 of a crafting table, in that order, the crafting output (filled repair kit) will only contain the first piece of cobble instead of both.

**Comment by SilentChaos512** [comment]
This affects other Silent Gear recipes as well, including gear crafting recipes. Any dynamic recipe, it seems. The output never gets updated after the first match.

**Comment by Shadows-of-Fire** [comment]
The criteria where a recipe would remain matching after an input change apparently was not considered, nor encountered, up until this point.  I'll probably have to make it where dynamic recipes always send an SPacketSetSlot.

**Comment by takashi1kun** [comment]
Can confirm that on version 4.5.0 of the mod, the issue with dynamic recipes persists

**Comment by P3pp3rF1y** [comment]
Sophisticated Backpacks dye recipes have their result disappear once second dye is put in the crafting grid.

Appears to be a line of code missing above this one which would simply get the new crafting result from recipe, now it just sends an empty ItemStack to client.
https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.16/src/main/java/shadows/fastbench/gui/ContainerFastBench.java#L83

**Comment by Shadows-of-Fire** [comment]
Yep that'd be it, sorry that took so long to get to.
