### ISSUE TITLE
[Bug] Placing any wood log in the inventory crafting table, causes client side crash only.

### ISSUE THREAD

**Issue by BastionNtB** [Shadows-of-Fire/FastWorkbench#61]
As the title says, creating a crafting table the recipe is fine, no crashes.

Minecraft: 1.16.4
Forge: 35.1.13
Mod: FastWorkbench-1.16.3-4.4.1.jar

Happened connected to a server, only client crashes, server remains up.

List of mods in error log.

Error log: https://pastebin.com/mt5j2jp9

**Comment by Shadows-of-Fire** [comment]
This sounds like a mod conflict, as that crash cannot happen in the presence of just FB and vanilla.  If it happens with just FB/forge, then it's probably something I can fix.

**Comment by BastionNtB** [comment]
Yeah apparently it's any item in the table, so kinda weird.

So, it turns out it was a mod conflict. Called 'Not Enough Creativity". Not sure what the issue is, but the mod has no config so it's not like I could go through and change a setting to see what worked. If anyone else has the same error "java.lang.ClassCastException: net.minecraft.inventory.CraftingInventory cannot be cast to shadows.fastbench.gui.CraftingInventoryExt"

Might be something to look into removing. Going to close this.
