### ISSUE TITLE
[1.16.5] Crash When Crafting in Inventory

### ISSUE THREAD

**Issue by coolsimulations** [Shadows-of-Fire/FastWorkbench#63]
Mod Version: FastWorkbench - 1.16.3 - 4.4.1
Forge Version: 1.16.5 - 36.0.0

Overview: I've been playing with the latest version of FastWorkbench on 1.16.4 for a while now. I've just updated to 1.16.5 using the same version and constantly experience a crash when placing an item inside the player inventory crafting grid. Crafting via a Crafting Table works though.

Steps to Reproduce:
1. Open your inventory in Survival
2. Place an item in the Crafting Grid
3. Crash Happens (only on client-side)

Crash Reports:
[crash-2021-01-16_11.20.05-client.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/5823642/crash-2021-01-16_11.20.05-client.txt)
[crash-2021-01-16_11.21.21-client.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/5823643/crash-2021-01-16_11.21.21-client.txt)
[crash-2021-01-16_11.34.58-client.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/5823644/crash-2021-01-16_11.34.58-client.txt)
Debug Log:
[debug.log](https://github.com/Shadows-of-Fire/FastWorkbench/files/5823646/debug.log)

**Comment by Shadows-of-Fire** [comment]
There's a 16.5?  That can't be stable yet, you should probably just not be using it for now.

**Comment by SzczurekYT** [comment]
This probably happened also to me on 1.16.4, forge 35.1.7
