### ISSUE TITLE
Crash when right clicking inventory crafting window

### ISSUE THREAD

**Issue by Cryotheus** [Shadows-of-Fire/FastWorkbench#68]
Got a crash report for you. I right clicked a stack of bones into my invetory crafting grid for this to transpire. I was connected to a multiplayer server when this happened.
[Original issue](https://github.com/YaLTeR/MouseTweaks/issues/43)
[crash-2021-01-23_21.49.23-client.txt](https://github.com/Shadows-of-Fire/FastWorkbench/files/5863553/crash-2021-01-23_21.49.23-client.txt)

**Comment by Shadows-of-Fire** [comment]
Update to 4.5.0 and determine if the issue persists
