### ISSUE TITLE
Some crafting recipes don't work

### ISSUE THREAD

**Issue by crazyirishwrencher** [Shadows-of-Fire/FastWorkbench#7]
I am unable to craft 9 pcs of lapis into a block. Also Botania's floral powder recipes doesn't work either. Both show up in JEI, but when put into a vanilla crafting grid, neither will show an output. Disabling this mod fixes the problem.

Duplicated with Forge Versions 2770 and 2765.

**Comment by Shadows-of-Fire** [comment]
I can't reproduce that not working in 2770, or the version i previously had in my development environment.  You must have something else modifying either the recipes themselves or the workbench.

**Comment by crazyirishwrencher** [comment]
Certainly possible. I spent awhile trying to nail it down. Heres a modlist.

Just Enough Items (JEI) (by mezz)
ConnectedTexturesMod (by tterrag1098)
Chisel (by tterrag1098)
Cathedral (by ferreusveritas)
Immersive Engineering (by BluSunrize)
Immersive Petroleum (by theFlaxbeard)
Immersive Tech (by ferroo2000)
Alternating Flux (by AntiBlueQuirk)
Mantle (by mDiyo)
Tinkers Construct (by mDiyo)
Tinkers' Tool Leveling (by bonusboni)
Tinker's JEI (by Possible_Triangle)
PlusTiC (by Landmaster_phuong0429)
Construct's Armory (by theillusivec4)
Armory Expansion (by YaibaToKen)
Shadowfacts' Forgelin (by shadowfactsmc)
Pewter (by ejektaflex)
Baubles (by azanor)
Thaumcraft (by azanor)
Thaumic JEI (by Buuz135)
Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
Thaumic Periphery (by mangoose3039)
Rustic (by mangoose3039)
Rustic Thaumaturgy (by Voxel_Friend)
Traverse (by ProfessorProspector)
Chameleon (by jaquadro)
Storage Drawers (by jaquadro)
CraftTweaker (by jaredlll08)
Inventory Tweaks (by Kobata)
Just a Few Fish (by Tmtravlr)
[SBM] Wooden Shears (by darkguardsman)
Giacomo's Foundry (by Zacomat)
Pam's HarvestCraft (by MatrexsVigil)
Farming for Blockheads (by BlayTheNinth)
Cooking for Blockheads (by BlayTheNinth)
OpenBlocks Elevator (by VsnGamer)
JEI Integration (by SnowShock35)
RandomTweaks (by TheRandomLabs)
Aroma1997Core (by Aroma1997)
AromaBackup (by Aroma1997)
Wearable Backpacks (by InsomniaKitten)
The Twilight Forest (by Benimatic)
Waystones (by BlayTheNinth)
AbyssalCraft (by Shinoow)
[ANGRY PIXEL] The Betweenlands (by MrCompost)
Roguelike Dungeons (by Greymerk)
Dynamic Surroundings (by OreCruncher)
Bookshelf (by Darkhax)
Enchanting Plus (by Darkhax)
Orbis API (by GildedGames)
The Aether II (by GildedGames)
Ender Compass (by MrIbby)
Chop Down Updated (by Shovinus)
AutoRegLib (by Vazkii)
Quark (by Vazkii)
Quark Oddities (by Vazkii)
Embers Rekindled (by BordListian)
Aetherworks (by v0idwa1k3r)
Soot (by BordListian)
Mystical Mechanics API (by BordListian)
Mystcraft (by XCompWiz)
Guidebook (by gigaherz)
Linking Through the Ages (LTTA) (by TheFloydman)
More Mystcraft (by TheFloydman)
Worley's Caves (by super_fluke50036)
Soul Shards Respawn (by TehNut)
Primitive Mobs (by Daveyx0)
LLibrary (by iLexiconn)
Mowzie's Mobs (by BobMowzie)
Ice and Fire: Dragons in a whole new light! (by alex1the1666)
Controlling (by jaredlll08)
AppleSkin (by squeek502)
Just Enough HarvestCraft (JEHC) (by mrAppleXZ)
Voidaic Arcania (by Inazuma262)
MMD OreSpawn (by jriwanek)
Base Metals (by jriwanek)
Reliquary v1.3 (by P3pp3rF1y)
MetalChests (by MegaT145)
Extra Alchemy (by zabi94)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
Engineer's Doors (by Nihiltres)
Botania (by Vazkii)
ExtraBotany (by ExtraMeteorP)
Astral Sorcery (by HellFirePvP)
Coterie Craft [16x] (by Cpt_Corn)
Better Foliage (by octarine_noise)
VanillaFix (by Runemoro)
GraveStone Mod (by EuhDawson)
Carry On (by Tschipp)
Clay Bucket (by abecderic)
The Beneath (by Shinoow)
The Erebus (by Vadis365)
InstantUnify (by MrRiegel)
WanionLib (by WanionCane)
UniDict (by WanionCane)
BetterFps (by Guichaguri)
Dirt2Path (by marwat208)
Inspirations (by KnightMiner)
Cosmetic Armor Reworked (by ZLainSama)
Dungeon Mobs Reborn (by Sunconure11)
SwingThroughGrass (by exidex)
Rough Mobs 2 (by Lellson)
Diet Hoppers (by RWTema)
FancyBlockOverlay (by UnknownTexture)
Familiar Fauna (by Glitchfiend)
FoamFix for Minecraft (by asiekierka)
MrCrayfish's Furniture Mod (by Mr_Crayfish)
Fullscreen Windowed (Borderless) for Minecraft (by hancin)
Hwyla (by TehNut)
Nature's Compass (by ChaosTheDude)
NetherPortalFix (by BlayTheNinth)
Pretty Beaches (by BlayTheNinth)
Scenter Mod (by MickKay)
Simple Storage Network (by Lothrazar)
Spartan Shields (by ObliviousSpartan)
XP From Harvest (by ReaIGecko)
Wawla - What Are We Looking At (by Darkhax)
Toast Control (by Shadows_of_Fire)
Vampirism - Become a vampire! (by maxanier)
Vampirism Integrations (by maxanier)
Sophisticated wolves (by NightKosh)
Villager Trade Tables (by csb987)
Akashic Tome (by Vazkii)
V-Tweaks (by oitsjustjose)
Fairy Lights (by pau101)
Project: Vibrant Journeys (by solis_nova123)
Placebo (by Shadows_of_Fire)
Botania Improved Textures (by blueyogaball)
LibrarianLib (by yrsegal)
Natural Pledge (by yrsegal)
JustEnoughIDs (by Runemoro)
Just Enough Resources (JER) (by Way2muchnoise)
Quick Leaf Decay (by lumien231)
Chunk-Pregenerator (by Speiger)
LagGoggles (by Terminator_NL)
JourneyMap (by techbrew)
Reborn Core (by modmuss50)
Steve's Carts Reborn (by modmuss50)
Additional Structures (by XxRexRaptorxX)
Bailey's Dailies (by ToroCraft)
Born in a Barn (by Speiger)
Electroblob's Wizardry (by electroblob)
Questionably Immersive (by theFlaxbeard)
DummyCore Unofficial (by TheLMiffy1111)
Thaumic Bases Unofficial (by Rumaruka)
Client Tweaks (by BlayTheNinth)
ArchitectureCraft - ElytraDev Version (by darkevilmac)
Garden Stuff (by jaquadro)
Level Up! Reloaded (by BeetoGuy)
