### ISSUE TITLE
[1.12.2] Recipe book not disabled

### ISSUE THREAD

**Issue by xJon** [Shadows-of-Fire/FastWorkbench#70]
Hi,
I wanted to switch out the No Recipe Book mod in my modpack for FastWorkbench, but for some reason, it does not successfully disable the recipe book (unlike No Recipe Book which does make it go poof).
I've checked and the config file of the mod is correctly set (`B:"Disable Recipe Book"=true`). There is no special error message in the log from the mod.
You can test yourself by downloading my modpack ([Technic](https://www.technicpack.net/modpack/the-1122-pack) | [CurseForge](https://www.curseforge.com/minecraft/modpacks/the-1122-pack)), and then manually removing the No Recipe Book mod and manually adding FastWorkbench.
Any idea why is this happening?
Thank you!

**Comment by Shadows-of-Fire** [comment]
1.12 has been so long ago that I don't even remember if it actually removes the button.  It should disable the functionality, however.  But 1.12 is end-of-life, so however it works is how it will work until the end of time.
