### ISSUE TITLE
2x2 crafting not showing any items in crafted box when on server

### ISSUE THREAD

**Issue by jakey1995abc** [Shadows-of-Fire/FastWorkbench#71]
When playing on a 1.16.5 paper server, if the client has this mod installed the inventory crafting (2x2) never shows what it is that you are crafting on the right hand side, but will still allow you to click and collect the crafted item.

**Comment by Shadows-of-Fire** [comment]
Is the mod present on the server?  I have no idea what paper is.

**Comment by jakey1995abc** [comment]
No, the mod is not on the server. Paper is a lightweight/highly optimised version of Bukkit and Spigot

**Comment by Shadows-of-Fire** [comment]
This mod must be on both sides to function properly.
