### ISSUE TITLE
Breaks Occultism's Storage Actuator Crafting Grid

### ISSUE THREAD

**Issue by recon88** [Shadows-of-Fire/FastWorkbench#73]
FastWorkbench seems to be conflicting with [Occultism](https://www.curseforge.com/minecraft/mc-mods/occultism).
The Crafting Grid of the Storage Actuator no longer outputs any recipe results as soon as you install FW.

[https://i.imgur.com/EM7S9rP.png](https://i.imgur.com/EM7S9rP.png)

**Comment by Shadows-of-Fire** [comment]
I guess I didn't account for the possibility of anyone else using these vanilla constructs.  I can check if the container in question is a vanilla container or not.

**Comment by Shadows-of-Fire** [comment]
Upon further inspection I cannot find a single area where anything from FB could impact that mod.  FB's changes are strictly to make the crafting table open a new GUI and some coremods that only target the PlayerContainer, and this mod does not extend PlayerContainer.
