### ISSUE TITLE
crafting resultant fails to render in inventory

### ISSUE THREAD

**Issue by CommieKiller3000** [Shadows-of-Fire/FastWorkbench#74]
![demo_1](https://user-images.githubusercontent.com/83923556/117585073-b2d4b200-b0cd-11eb-939b-8fa8bfdbb27a.gif)

The visual issue is exclusive to the player's inventory. I don't believe this is intentional. The GIF above demonstrates the issue while playing in a multiplayer server (IP:simplyvanilla.net).

**Comment by Shadows-of-Fire** [comment]
do you have any other mods messing with the slot (see #65 )

This doesnt happen with just FB

**Comment by CommieKiller3000** [comment]
Ah, yes, I do! I am using the latest version of JEI for version 1.16.4.  If I skimmed the thread correctly, the issue is that I'm using JEI when I should be using a patched version of NEC, or is this still a pending issue?

**Comment by CommieKiller3000** [comment]
I installed NEC, and the rendering issue was still present. Uninstalling both as well as trying each one at a time did not fix the issue either. I have a plethora of other mods, so one of them may very well be the cause. It's likely not your bother but is instead an issue with the combination of mods I'm using.

**Comment by Aceplante** [comment]
Im having this issue too 1.18.2

Edit: likely becuase it is not on the server side?

**Comment by iTrooz** [comment]
I also had this issue (Forge 1.16.5)
In the end, the problem was that I only installed this mod on the server side, and not the client side

@Shadows-of-Fire is this behaviour normal ? If so, could you please update the description on curseforge to mention that the mod should be installed on both sides ?

**Comment by NagrandHero** [comment]
I have this issue as well when using it client-side only.

**Comment by Shadows-of-Fire** [comment]
Using FB on a single has has never been and never will be supported

**Comment by iTrooz** [comment]
Is there any reason for that ? A specific technical limitation ?

**Comment by Shadows-of-Fire** [comment]
FB performs (at a high level) an optimization that reduces the number of total recipe match lookups on the server to just 1, and on the client to zero.  This is done by having the server do one lookup, caching it, and sending the result to the client via packet.  If FB is absent on the client, the packet cannot be read, and if absent on the server, the packet will not be sent.

**Comment by iTrooz** [comment]
Okay !

Switching subject. Referencing my earlier comment:
> If so, could you please update the description on curseforge to mention that the mod should be installed on both sides ?

Do you think it'd be possible to do that ? I think it would help people confused by the glitch shown above

**Comment by Aceplante** [comment]
> FB performs (at a high level) an optimization that reduces the number of total recipe match lookups on the server to just 1, and on the client to zero. This is done by having the server do one lookup, caching it, and sending the result to the client via packet. If FB is absent on the client, the packet cannot be read, and if absent on the server, the packet will not be sent.

or maybe mention this too
