### ISSUE TITLE
crash with jei upon using the "put items in crafting table" feature

### ISSUE THREAD

**Issue by thelegitdolt** [Shadows-of-Fire/FastWorkbench#76]
crash report - https://gist.github.com/thelegitdolt/80283ca9844c187a2cb645904602a0b0
logs - https://gist.github.com/thelegitdolt/22fb1c5ec1fb677390961d77801c16ad

**Comment by Shadows-of-Fire** [comment]
You'll need to report this to polymorph, their integration is outdated.

**Comment by thelegitdolt** [comment]
thought this was jei. thank you.

**Comment by thelegitdolt** [comment]
for the swift response as well
