### ISSUE TITLE
Crumbs workbenches

### ISSUE THREAD

**Issue by I3estOFF** [Shadows-of-Fire/FastWorkbench#77]
Hello!
I have workbenches made of other minecraft wood like spruce. This is possible with Crumbs mod. But they are still slow :D 
I guess they don't work with your mod, so if you can, please make it compatible :)))
![image](https://user-images.githubusercontent.com/63112899/144032306-50e72e84-81e3-4afa-aae2-b0c0dabc33d2.png)

**Comment by Shadows-of-Fire** [comment]
As of 4.6.0 FWB edits the vanilla code to increase crafting speed.  If this still does not work for that mod's crafting tables, it is a bug in *that mod*.

However, you may be able to use [FastSuite](https://www.curseforge.com/minecraft/mc-mods/fastsuite) to receive some benefit in those tables.
