### ISSUE TITLE
Mod Interaction

### ISSUE THREAD

**Issue by Cazadorsniper** [Shadows-of-Fire/FastWorkbench#8]
I found that this issue happens when Erebus is installed: https://github.com/Shadows-of-Fire/FastWorkbench/issues/7

**Comment by Shadows-of-Fire** [comment]
is erebus creating weird recipes?  I can't think of anything that causes recipe to spontaneously vanish unless something is manipulating it

**Comment by Cazadorsniper** [comment]
Making attempts to fix at the moment, I just posted this to let you know why #7 happened.

**Comment by Cazadorsniper** [comment]
Fixed the issue. Closing this now.
