### ISSUE TITLE
[bug] Shift-craft custom recipe may cause infinite loop.

### ISSUE THREAD

**Issue by khjxiaogu** [Shadows-of-Fire/FastWorkbench#80]
If a recipe whose `getCraftingResult` return EMPTY while `matches` return true, crafting this recipe would cause the game stucks. I know this is incorrect but this won't cause trouble without FastWorkBench. Adding one more check would improve compatibility and robustness.

**Comment by Shadows-of-Fire** [comment]
That's not supported behavior, the only thing I might do is fire a proper exception.

**Comment by khjxiaogu** [comment]
> That's not supported behavior, the only thing I might do is fire a proper exception.

Maybe do another check, log a warning and break that loop would be more friendly.
