### ISSUE TITLE
[1.18.2] Config option to disable workbench tooltip.

### ISSUE THREAD

**Issue by KKotik** [Shadows-of-Fire/FastWorkbench#84]
When I installed the mod the tooltip is appearing on my crafting table's tooltip, I assume it is added by this mod and suggest to at least to have option to disable it.

**Comment by jacket430** [comment]
I would like this too. Although I don't mind the tooltip, I would prefer if it wasn't there.

**Comment by Shadows-of-Fire** [comment]
Closed via #85
