### ISSUE TITLE
incompability issue with advent of ascension mod

### ISSUE THREAD

**Issue by HazardEST** [Shadows-of-Fire/FastWorkbench#86]
Mod Version
FastWorkbench-1.16.5-4.6.1
AoA3 1.16.5-3.6.3

Describe the bug
FastWorkBench mod causes the lvl 55 extraction ability to not work.

To Reproduce
Steps to reproduce the behaviour:

Make sure you have atleast lvl 55 extraction and the "Auto Enchant Crafting" ability isn't greyed out.
Craft any tool in crafting table, I went with diamond pickaxe.
The resulting item won't have the enchants that it should, giving you an unenchanted item.

Expected behavior
The tool in crafting table is supposed to have Unbreaking III and Fortune III.

Screenshots
Vanilla
https://i.imgur.com/kkjUtG5.png

FastWorkBench
https://i.imgur.com/UDyufOV.png

**Comment by Shadows-of-Fire** [comment]
You need to file this on advent's side, this isn't fixable unless there is a specific compat change that needs to be made on my end

**Comment by Shadows-of-Fire** [comment]
Closing as 1.16.5 is no longer supported
