### ISSUE TITLE
[1.18.2 bug] Quark backpack prevents shift-clicking recipes into inventory

### ISSUE THREAD

**Issue by MaoDoBan** [Shadows-of-Fire/FastWorkbench#87]
I have this issue on my survival server, and today I found the causes of this bug.

The bug related on quark repositorie:
https://github.com/VazkiiMods/Quark/issues/3671

My comment with video demonstration:
https://github.com/VazkiiMods/Quark/issues/3671#issuecomment-1132960701

**Comment by Shadows-of-Fire** [comment]
Fixed in 6.1.0
