### ISSUE TITLE
Conflict with crafting table multiblocks

### ISSUE THREAD

**Issue by krisjenner** [Shadows-of-Fire/FastWorkbench#9]
Hey,

I'm using a [Sponge plugin](https://ore.spongepowered.org/DosMike/EquivalentMatterExchange) that uses a workbench and a daylight sensor as a multiblock to add a custom GUI - however with this mod installed it fails to work. Is there anything you could add in config to disable on the server side or something?

I understand this isn't really your mods problem but was hoping for some help.

Thanks

**Comment by Shadows-of-Fire** [comment]
Disabling the mod serverside... well, you may as well just uninstall it at that point.
I'll go talk to the author of the plugin about options.
