### ISSUE TITLE
Mod compat issue

### ISSUE THREAD

**Issue by DerekM07** [Shadows-of-Fire/FastWorkbench#90]
I'm having a problem developing a mod of my own. I ran into an issue while testing alongside FastWorkbench (4.6.1 for 1.16.5).

I created a handler for PlayerEvent.ItemCraftedEvent and it was working fine, but with FastWorkbench also installed I'm finding that it's not working because event.getCrafting().getItem() returns Items.AIR instead of the actual output item.

This would impact any other mods utilizing that event, I would think. Can you possibly look into this?

**Comment by Shadows-of-Fire** [comment]
Unfortunately 1.16.5 is out of support, so no changes will be made to that version.

What were you trying to achieve?  There may be alternatives.

**Comment by DerekM07** [comment]
You should reconsider that, being that FastWorkbench has millions of downloads and 1.16.5 continues to have millions of players who aren't moving on yet--and I believe you've effectively broken a forge event.

Anything I (or others) are trying to achieve in an onItemCrafted method is going to require retrieval of the output item in the recipe, so I'm not sure what alternatives there'd possibly be.

If I release the mod I'm working on, I can just recommend players use FastSuite as an alternative, but I'd think fixing this is preferable to all parties.

**Comment by DerekM07** [comment]
You should at least check if this is borked in the version you care about keeping updated. You're welcome.
