### ISSUE TITLE
Incorrect crafting results from Vanilla recipes when using FastWorkBench

### ISSUE THREAD

**Issue by alcatrazEscapee** [Shadows-of-Fire/FastWorkbench#92]
Observe the following setup (Crafting firework stars, with two gunpowder, two dye, and one diamond placed in the crafting grid):

![before](https://user-images.githubusercontent.com/35673674/195996464-76ee61f8-7193-4262-8fea-cff7916bba74.png)

In vanilla, if you were to take these items out one by one, you receive one "Firework Star - Small Ball, Blue" and one "Firework Star - Small Ball, Blue, Trail".  **Alternatively** if you shift+click these items out, you get the same result: two different items. See below:

![without](https://user-images.githubusercontent.com/35673674/195996301-1a1d5d3e-80c7-4d63-8339-63a4396e8216.png)

**However** with FastWorkBench installed, if you shift click this, you get a different result: Two "Firework Star - Small Ball, Blue, Trail"s. You've effectively used one diamond for two recipes.

![fwb](https://user-images.githubusercontent.com/35673674/195996344-b40ee54c-4525-4245-8a9d-2e94fb00f389.png)

### Mods

- Fast Workbench 1.19.2-7.0.0
- Placebo 1.19.2-7.0.0

### Why

Fast Workbench makes the incorrect assumption that a recipe's results are independent of the crafting grid. As such, it never updates the result item and just blindly trusts the last result. This is **incorrect**, as seen here in vanilla, at least for recipes that have `isSpecial()` marked.

I encountered this in a conflict with one of my mods in 1.18.2, where we have a recipe that has a similar property - adjusting the count of the output based on the crafting inputs. Which then led to a duplication glitch.

**Comment by Shadows-of-Fire** [comment]
FastWorkbench does not make that assumption and has explicit code for updating special recipes here https://github.com/Shadows-of-Fire/FastWorkbench/blob/1.18/src/main/java/shadows/fastbench/util/FastBenchUtil.java#L49

The question is then "why isnt it working", because this code was introduced to fix this exact issue, which it did fix at the time of implementation

**Comment by alcatrazEscapee** [comment]
From the looks of it, you never call it during the operative loop while creating outputs. `craftMatrix.checkChanges = false;` is set at the beginning of the loop, which presumably prevents any calls during said loop, and it's only invoked once at the end of the while loop.

https://github.com/Shadows-of-Fire/FastWorkbench/blob/0db466628ba657dbd30f3cda1cc05ff00162c983/src/main/java/shadows/fastbench/util/FastBenchUtil.java#L85-L104

**Comment by Shadows-of-Fire** [comment]
That does appear to be the case.  Fix should be a simple insertion of the earlier logic into this loop.  I'm wondering how nobody has run into this yet.

**Comment by Shadows-of-Fire** [comment]
Confirmed as reproducible in versions as far back as MC 1.12.2
