### ISSUE TITLE
[1.19.2] Polymorph Mod no longer functions with mod active.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/FastWorkbench#93]
Title^

Polymorph Mod does not show the conflict button whenever there is one.

Versions: 7.0.0 | https://www.curseforge.com/minecraft/mc-mods/fastworkbench/files/4028347

MC: 1.19.2
Forge: 43.1.39

**Comment by Shadows-of-Fire** [comment]
This functionality was always implemented by polymorph.  Please ask them to reimplement since fb is now updated.

**Comment by Gbergz** [comment]
Ah, gotcha.
Will ask there.
