### ISSUE TITLE
Bug: Setting "Remove Recipe Book Button" to true while displayed does not hide the recipe book

### ISSUE THREAD

**Issue by lynnpye** [Shadows-of-Fire/FastWorkbench#96]
Forge 43.2.8
FastWorkbench 1.19.2-7.1.0
Placebo 1.19.2-7.1.7

Set:
B:"Remove Recipe Book Button"=false
in fastbench.cfg.

Create new world. Open inventory with 2x2 crafting grid. Click recipe book button to show recipe book. Close inventory without closing recipe book. Save and Quit.

Set:
B:"Remove Recipe Book Button"=true
in fastbench.cfg.

Reopen world. Open inventory with 2x2 crafting grid. Recipe book is still displayed but recipe book button is hidden.

**Comment by Shadows-of-Fire** [comment]
This is... sorta on the "not a bug" line, the config only removes the button, because it's really intrusive to do anything else.  If you open the recipe book and disable the button, that's on you.

**Comment by lynnpye** [comment]
That's fair. :)
